# Generated by Django 6.0.4 on 2026-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('inapp', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField(help_text='Puede incluir {variables}')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('inapp', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='inapp', max_length=10)),
                ('leida', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=10)),
                ('error', models.TextField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-creada'],
                'indexes': [models.Index(fields=['usuario_id', '-creada'], name='notificacio_usuario_776bc1_idx'), models.Index(fields=['leida'], name='notificacio_leida_23b9c2_idx'), models.Index(fields=['estado'], name='notificacio_estado_c2bcaa_idx')],
            },
        ),
    ]
